DoctorPatient/DoctorPatient/Controllers/RegisteredUsersController.cs
using DoctorPatient.Infrastructure;
using DoctorPatient.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace DoctorPatient.Controllers
{
    public class RegisteredUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /RegisteredUser/
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var users = db.ApplicationUsers;    //Users to Applicationusers
            var model = new List<EditUserViewModel>();
            foreach (var user in users)
            {
                var u = new EditUserViewModel(user);
                model.Add(u);
            }
            return View(model);
        }

        // GET: /RegisteredUser/Details/userName
        [Authorize]
        public ActionResult Details(/*string userId*/)
        {
            //string id = User.Identity.Name;
            string userId = User.Identity.GetUserId();
            var db = new ApplicationDbContext();
            //var user = Db.ApplicationUsers.First(u => u.UserName == id);
            //var model = new EditUserViewModel(user);
            //model.Appointments.Sort();
            var user = db.ApplicationUsers.Find(userId);
            EditUserViewModel model = new EditUserViewModel
            {
                Appointments = user.Appointments,
                Address = user.Address,
                Name = user.Name,
                BirthDate = user.BirthDate,
                Blocked = user.Blocked,
                Sex = user.Sex,
                UserName = user.UserName
            };

            return View(model);
        }

        // GET: /RegisteredUser/Edit/userName
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id, DoctorPatient.Controllers.AccountController.ManageMessageId? Message = null)
        {
            var Db = new ApplicationDbContext();
            var user = Db.ApplicationUsers.First(u => u.UserName == id);
            var model = new EditUserViewModel(user);
            ViewBag.MessageId = Message;
            return View(model);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Db = new ApplicationDbContext();
                var user = Db.ApplicationUsers.First(u => u.UserName == model.UserName);

                // Update the user data:
                user.Name = model.Name;
                user.Address = model.Address;
                user.BirthDate = model.BirthDate;
                user.Sex = model.Sex;
                user.Appointments = model.Appointments;
                user.Blocked = model.Blocked;
                Db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                await Db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        // GET: /RegisteredUser/Delete/5
        [Authorize(Roles = "Admin, Patient")]
        public ActionResult Delete(string id = null)
        {
            var Db = new ApplicationDbContext();
            var user = Db.ApplicationUsers.First(u => u.UserName == id);
            var model = new EditUserViewModel(user);
            if (user == null)
            {
                return View("Error");
            }
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Patient")]
        public ActionResult DeleteConfirmed(string id)
        {
            var Db = new ApplicationDbContext();
            var user = Db.ApplicationUsers.First(u => u.UserName == id);
            Db.Users.Remove(user);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //USER ROLES!!
        [Authorize(Roles = "Admin")]
        public ActionResult UserRoles(string id)
        {
            var Db = new ApplicationDbContext();
            var user = Db.ApplicationUsers.First(u => u.UserName == id);
            var model = new SelectUserRolesViewModel(user);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult UserRoles(SelectUserRolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var idManager = new IdentityManager();
                var Db = new ApplicationDbContext();
                var user = Db.ApplicationUsers.First(u => u.UserName == model.UserName);
                idManager.ClearUserRoles(user.Id);
                foreach (var role in model.Roles)
                {
                    if (role.Selected)
                    {
                        idManager.AddUserToRole(user.Id, role.RoleName);
                    }
                }
                return RedirectToAction("index");
            }
            return View();
        }
    }
}

DoctorPatient/DoctorPatient/Views/RegisteredUsers/Delete.cshtml
@model DoctorPatient.Models.EditUserViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
            <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
        </div>
    }
</div>

DoctorPatient/DoctorPatient/Views/RegisteredUsers/Details.cshtml
@model DoctorPatient.Models.EditUserViewModel

@{
    ViewBag.Title = "My Appointments";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.Label("Delete Account")
        </dt>
        <dd>
            @Html.ActionLink("Click Here to Delete", "Delete", new { id = Model.UserName })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appointments)
        </dt>

        <dd>
            <table class="table">
                <tr>
                    <th>Doctor's Name</th>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
                @foreach (var item in Model.Appointments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Doctor.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Time)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { Controller = "Appointment", Action = "Edit", id = item.AppointmentID }) |
                            @Html.ActionLink("Details", "Details", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID }) |
                            @Html.ActionLink("Delete", "Delete", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID })
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
</p>

DoctorPatient/DoctorPatient/Views/RegisteredUsers/Edit.cshtml
@model DoctorPatient.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EditUserViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDate)
            @Html.ValidationMessageFor(model => model.BirthDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sex)
        </div>
        <div class="editor-field">
            @Html.EnumDropDownListFor(model => model.Sex)
            @Html.ValidationMessageFor(model => model.Sex)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Blocked)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Blocked, new SelectList(
        new[]
        {
            new { Value = "true", Text = "Yes" },
            new { Value = "false", Text = "No" },
        },
        "Value",
        "Text",
        Model
    ))
            @Html.ValidationMessageFor(model => model.Blocked)
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn btn-default" /> |
            @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
            <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorPatient/DoctorPatient/Views/RegisteredUsers/Index.cshtml
@model IEnumerable<DoctorPatient.Models.EditUserViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.UserName }) |
            @Html.ActionLink("Assign Role", "UserRoles", new { id = item.UserName }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.UserName })
        </td>
    </tr>
}

</table>

DoctorPatient/DoctorPatient/Views/RegisteredUsers/UserRoles.cshtml
@model DoctorPatient.Models.SelectUserRolesViewModel

@{
    ViewBag.Title = "User Roles";
}

<h2>Roles for user @Html.DisplayFor(model => model.UserName)</h2>
<hr />

@using (Html.BeginForm("UserRoles", "RegisteredUsers", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserName)
            </div>
        </div>

        <h4>Select Role Assignments</h4>
        <br />
        <hr />

        <table>
            <tr>
                <th>
                    Select
                </th>
                <th>
                    Role
                </th>
            </tr>
            @Html.EditorFor(model => model.Roles)
        </table>
        <br />
        <hr />

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn btn-default" /> |
            @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
            <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
        </div>
    </div>
}