DoctorPatient/DoctorPatient/Controllers/DoctorController.cs
using DoctorPatient.Infrastructure;
using DoctorPatient.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace DoctorPatient.Controllers
{
    public class DoctorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Doctors/
        public ActionResult Index(string docDept, string searchstring)
        {
            var deptList = new List<Enums.HospitalDepartment>();
            deptList = Enum.GetValues(typeof(Enums.HospitalDepartment))
                                    .Cast<Enums.HospitalDepartment>()
                                    .ToList();
            ViewBag.docDept = new SelectList(deptList);

            var doctors = from d in db.Doctors
                          select d;

            if (!string.IsNullOrEmpty(searchstring))
            {
                doctors = doctors.Where(s => s.Name.Contains(searchstring));
            }

            if (!string.IsNullOrEmpty(docDept))
            {
                doctors = doctors.Where(x => x.Department.ToString() == docDept);
            }
            return View(doctors);
        }

        //Doctor Availability
        public ActionResult Availability(int id)
        {
            DoctorModel doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return View("Error");
            }
            AppointmentModel test = new AppointmentModel
            {
                DoctorID = id
            };
            ViewBag.TimeBlockHelper = new SelectList(String.Empty);
            ViewBag.DoctorName = doctor.Name;
            return View(test);
        }

        // GET: /Doctors/UpcomingAppointments/5
        [Authorize(Roles = "Admin, Doctor")]
        public ActionResult UpcomingAppointments(string id, string SearchString)
        {
            int n;
            bool isInt = int.TryParse(id, out n);
            if (!isInt)
            {
                var user = db.ApplicationUsers.First(u => u.UserName == id);
                var model = new EditUserViewModel(user);
                DoctorModel doctor = db.Doctors.First(u => u.Name == user.Name);
                if (doctor == null)
                {
                    return View("Error");
                }
                if (!String.IsNullOrEmpty(SearchString))
                {
                    doctor.Appointments = doctor.Appointments.Where(s => s.ApplicationUser.Name.ToUpper().Contains(SearchString.ToUpper())).ToList();
                }
                doctor.Appointments.Sort();
                return View(doctor);
            }
            else
            {
                if (!User.IsInRole("Admin"))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DoctorModel doctor = db.Doctors.Find(n);
                if (doctor == null)
                {
                    return View("Error");
                }
                doctor.Appointments.Sort();
                return View(doctor);
            }
        }

        // GET: /Doctors/History
        [Authorize(Roles = "Admin, Doctor")]
        public ActionResult History(string id)
        {
            int n;
            bool isInt = int.TryParse(id, out n);
            if (!isInt)
            {
                var user = db.ApplicationUsers.First(u => u.UserName == id);
                var model = new EditUserViewModel(user);
                DoctorModel doctor = db.Doctors.First(u => u.Name == user.Name);
                if (doctor == null)
                {
                    return View("Error");
                }
                doctor.Appointments.Sort();
                return View(doctor);
            }
            else
            {
                if (!User.IsInRole("Admin"))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DoctorModel doctor = db.Doctors.Find(n);
                if (doctor == null)
                {
                    return View("Error");
                }
                doctor.Appointments.Sort();
                return View(doctor);
            }
        }

        // GET: /Doctors/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more UpcomingAppointments see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,BirthDate,Sex,Department,Degree")] DoctorModel doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: /Doctors/Edit/5
        [Authorize(Roles = "Admin, Doctor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoctorModel doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return View("Error");
            }
            return View(doctor);
        }

        // POST: /Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more UpcomingAppointments see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin, Doctor")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,BirthDate,Sex,Department,Degree,DisableNewAppointments")] DoctorModel doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: /Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoctorModel doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return View("Error");
            }
            return View(doctor);
        }

        // POST: /Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DoctorModel doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorPatient/DoctorPatient/Views/Doctor/Availability.cshtml
@model DoctorPatient.Models.AppointmentModel

@{
    ViewBag.Title = "Doctor Availability";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Availability</h4>
        <hr />
        <div class="form-group">
            @Html.Label("Doctor's Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label((string)ViewBag.DoctorName, new { @class = "control-label col-md-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Available Appointments", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TimeBlockHelper", String.Empty)
                @Html.ValidationMessageFor(model => model.Time)
            </div>
        </div>
    </div>
}

<div>
    @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#TimeBlockHelper').append($("<option></option>").val("placeholder").text("Select Date"));
            $('#TimeBlockHelper').val("placeholder");
            $("#TimeBlockHelper").prop("disabled", true);
            $("#Date").change(function () {
                if ($("#Date").val() != "") {
                    var options = {};
                    options.url = "/Appointment/GetAvailableAppointments";
                    options.type = "POST";
                    options.data = JSON.stringify({ docID: '@Model.DoctorID', Date: $("#Date").val() });
                    options.dataType = "json";
                    options.contentType = "application/json";
                    options.success = function (data) {
                        data = $.map(data, function (item, a) {
                            return "<option value=" + item.Value + ">" + item.Text + "</option>";
                        });

                        $("#TimeBlockHelper").html(data.join(""));
                        $("#TimeBlockHelper").prop("disabled", false);
                    };
                    options.error = function () { alert("Error retrieving available appointments!"); };
                    $.ajax(options);
                }
                else {
                    $("#TimeBlockHelper").empty();
                    $('#TimeBlockHelper').append($("<option></option>").val("placeholder").text("Select Date"));
                    $('#TimeBlockHelper').val("placeholder");
                    $("#TimeBlockHelper").prop("disabled", true);
                }
            });
        });
    </script>
}

DoctorPatient/DoctorPatient/Views/Doctor/Create.cshtml
@model DoctorPatient.Models.DoctorModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Doctor Account</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sex)
                @Html.ValidationMessageFor(model => model.Sex)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Department)
                @Html.ValidationMessageFor(model => model.Department)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Degree)
                @Html.ValidationMessageFor(model => model.Degree)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorPatient/DoctorPatient/Views/Doctor/Delete.cshtml
@model DoctorPatient.Models.DoctorModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoctorPatient/DoctorPatient/Views/Doctor/Edit.cshtml
@model DoctorPatient.Models.DoctorModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate)
                @Html.ValidationMessageFor(model => model.BirthDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sex)
                @Html.ValidationMessageFor(model => model.Sex)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Department)
                @Html.ValidationMessageFor(model => model.Department)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Degree)
                @Html.ValidationMessageFor(model => model.Degree)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisableNewAppointments, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DisableNewAppointments, new SelectList(new[]
           {
            new { Value = "true", Text = "Yes" },
            new { Value = "false", Text = "No" },
        },
        "Value",
        "Text",
        Model
    ))
                @Html.ValidationMessageFor(model => model.DisableNewAppointments)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorPatient/DoctorPatient/Views/Doctor/History.cshtml
@model DoctorPatient.Models.DoctorModel

@{
    ViewBag.Title = "Appointment Hitory";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Appointments)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Patient Name</th>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
                @foreach (var item in Model.Appointments)
                {
                    if (item.Date.Date.Add(item.Time.TimeOfDay).CompareTo(DateTime.Now) < 0)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Time)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID }) |
                                @Html.ActionLink("Delete", "Delete", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID })
                            </td>
                        </tr>
                    }
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
</p>

DoctorPatient/DoctorPatient/Views/Doctor/Index.cshtml
@model IEnumerable<DoctorPatient.Models.DoctorModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<p>
    @using (Html.BeginForm("Index", "Doctor", FormMethod.Get))
    {
    <p> Title: @Html.TextBox("SearchString") Department: @Html.DropDownList("docDept", "All")<br /> </p>
        <p><input type="submit" value="Filter" /></p>
    }
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisableNewAppointments)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sex)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Degree)
                </td>
                <td>
                    @(item.DisableNewAppointments ? "Yes" : "No")
                </td>


                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Upcoming Appointments", "UpcomingAppointments", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                }
                else
                    if ((item.DisableNewAppointments ? "Yes" : "No") == "No")
                    {
                        <td>
                            @Html.ActionLink("Check Availability", "Availability", new { Controller = "Doctor", Action = "Availability", id = item.ID })
                        </td>
                    }

            </tr>
        }

    </table>

DoctorPatient/DoctorPatient/Views/Doctor/UpcomingAppointments.cshtml
@model DoctorPatient.Models.DoctorModel

@{
    ViewBag.Title = "Upcoming Appointments";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayName("Search Patient")
        </dt>
        <dd>
            @using (Html.BeginForm())
            {
                @Html.TextBox("SearchString")
                <input type="submit" value="Filter" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appointments)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Patient Name</th>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
                @foreach (var item in Model.Appointments)
                {
                    if (item.Date.Date.Add(item.Time.TimeOfDay).CompareTo(DateTime.Now) > 0)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Time)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID }) |
                                @Html.ActionLink("Delete", "Delete", new { Controller = "Appointment", Action = "Details", id = item.AppointmentID })
                            </td>
                        </tr>
                    }
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    @*Use the browser's internal history. Otherwise Redirectin to all Appointments*@
    <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
</p>