DoctorPatient/DoctorPatient/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DoctorPatient.Models
{
    public class Order
    {
        [DisplayName("Order Id")]
        public int OrderId { get; set; }
        [DisplayName("User")]
        public string UserId { get; set; }
        [DisplayName("Deliver to")]
        public string DeliveryName { get; set; }
        public Address DeliveryAddress { get; set; }
        [DisplayName("Total Price")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal TotalPrice { get; set; }
        [DisplayName("Time of Order")]
        public DateTime DateCreated { get; set; }
        public List<OrderLine> OrderLines
        {
            get; set;
        }
    }
}

DoctorPatient/DoctorPatient/Controllers/CartController.cs
using DoctorPatient.Models;
using DoctorPatient.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorPatient.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            Cart cart = Cart.GetCart();
            CartViewModel viewModel = new CartViewModel
            {
                CartLines = cart.GetCartLines(),
                TotalCost = cart.GetTotalCost()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(int id, int quantity)
        {
            Cart cart = Cart.GetCart();
            cart.AddToCart(id, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCart(CartViewModel viewModel)
        {
            Cart cart = Cart.GetCart();
            cart.UpdateCart(viewModel.CartLines);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveLine(int id)
        {
            Cart cart = Cart.GetCart();
            cart.RemoveLine(id);
            return RedirectToAction("Index");
        }
        public ActionResult Summary()
        {
            Cart cart = Cart.GetCart();
            CartSummaryViewModel viewModel = new CartSummaryViewModel
            {
                NumberOfItems = cart.GetNumberOfItems(),
                TotalCost = cart.GetTotalCost()
            };
            return PartialView(viewModel);
        }
    }
}

DoctorPatient/DoctorPatient/Controllers/OrdersController.cs
using DoctorPatient;
using DoctorPatient.Infrastructure;
using DoctorPatient.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DoctorPatient.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Orders
        public ActionResult Index(string orderSearch, string startDate, string endDate, string orderSortOrder)
        {
            var orders = db.Orders.OrderBy(o => o.DateCreated).Include(o => o.OrderLines);
            if (User.IsInRole("Patient"))
            {
                return View(db.Orders.Where(o => o.UserId == User.Identity.Name));
            }
            if (!String.IsNullOrEmpty(orderSearch))
            {
                orders = orders.Where(o => o.OrderId.ToString().Equals(orderSearch) ||
                o.UserId.Contains(orderSearch) || o.DeliveryName.Contains(orderSearch) ||
                o.DeliveryAddress.AddressLine1.Contains(orderSearch) ||
                o.DeliveryAddress.AddressLine2.Contains(orderSearch) ||
                o.DeliveryAddress.Town.Contains(orderSearch) ||
                o.DeliveryAddress.Province.Contains(orderSearch) ||
                o.DeliveryAddress.PostCode.Contains(orderSearch) ||
                o.TotalPrice.ToString().Equals(orderSearch) ||
                o.OrderLines.Any(ol => ol.ProductName.Contains(orderSearch)));
            }
            DateTime parsedStartDate;
            if (DateTime.TryParse(startDate, out parsedStartDate))
            {
                orders = orders.Where(o => o.DateCreated >= parsedStartDate);
            }
            DateTime parsedEndDate;
            if (DateTime.TryParse(endDate, out parsedEndDate))
            {
                orders = orders.Where(o => o.DateCreated <= parsedEndDate);
            }

            ViewBag.DateSort = String.IsNullOrEmpty(orderSortOrder) ? "date" : "";
            ViewBag.UserSort = orderSortOrder == "user" ? "user_desc" : "user";
            ViewBag.PriceSort = orderSortOrder == "price" ? "price_desc" : "price";
            ViewBag.CurrentOrderSearch = orderSearch;
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;

            switch (orderSortOrder)
            {
                case "user":
                    orders = orders.OrderBy(o => o.UserId);
                    break;
                case "user_desc":
                    orders = orders.OrderByDescending(o => o.UserId);
                    break;
                case "price":
                    orders = orders.OrderBy(o => o.TotalPrice);
                    break;
                case "price_desc":
                    orders = orders.OrderByDescending(o => o.TotalPrice);
                    break;
                case "date":
                    orders = orders.OrderBy(o => o.DateCreated);
                    break;
                default:
                    orders = orders.OrderByDescending(o => o.DateCreated);
                    break;
            }
            return View(orders);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Include(o => o.OrderLines).SingleOrDefault(o => o.OrderId == id);
            if (order == null)
            {
                return HttpNotFound();
            }

            if (order.UserId == User.Identity.Name || User.IsInRole("Admin"))
            {
                return View(order);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
        }

        


        // GET: Orders/Create
        public ActionResult Review()
        {
            Cart cart = Cart.GetCart();
            Order order = new Order();
            order.UserId = User.Identity.Name;
            var userId = User.Identity.GetUserId();
            var currentUser = db.ApplicationUsers.Find(userId);
            //ApplicationUser user = await UserManager.FindByNameAsync(order.UserId);
            order.DeliveryName = currentUser.Name;
            order.DeliveryAddress = currentUser.Address;
            order.OrderLines = new List<OrderLine>();
            foreach (var cartLine in cart.GetCartLines())
            {
                OrderLine line = new OrderLine
                {
                    Product = cartLine.Product,
                    ProductId = cartLine.ProductId,
                    ProductName = cartLine.Product.Name,
                    Quantity = cartLine.Quantity,
                    UnitPrice = cartLine.Product.Price
                };
            }
            //if (ModelState.IsValid)
            //{
            //    var body = "Email from App dev ";
            //    var message = new MailMessage();
            //    message.To.Add(new MailAddress("appdevproject18@gmail.com"));
            //    message.Subject = "Pet Clinic & Shop (Your Order(s))";
            //    message.Body = string.Format(body, order.UserId, order.DeliveryName, order.DeliveryAddress,
            //        order.OrderLines);
            //    using (var smtp = new SmtpClient())
            //    {
            //        await smtp.SendMailAsync(message);
            //        return RedirectToAction("Your order details have been emailed");
            //    }
            //}
            order.TotalPrice = cart.GetTotalCost();
            return View(order);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,UserId,DeliveryName,DeliveryAddress,TotalPrice,DateCreated")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.DateCreated = DateTime.Now;
                db.Orders.Add(order);
                db.SaveChanges();

                //add the orderlines to the database after creating the order
                Cart cart = Cart.GetCart();
                order.TotalPrice = cart.CreateOrderLines(order.OrderId);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = order.OrderId });
            }

            return RedirectToAction("Review");
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserId,DeliveryName,DeliveryAddress,TotalPrice,DateCreated")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorPatient/DoctorPatient/Views/Orders/Delete.cshtml
@model DoctorPatient.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoctorPatient/DoctorPatient/Views/Orders/Details.cshtml
@model DoctorPatient.Models.Order
@{
    ViewBag.Title = "Order Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <h4>Item(s)</h4>
        </div>
        <div class="col-md-2">
            <h4>Quantity</h4>
        </div>
        <div class="col-md-2">
            <h4>Unit Price</h4>
        </div>
    </div>
    @foreach (var item in Model.OrderLines)
    {
        <div class="row">
            <div class="col-md-8">

            </div>
            <div class="col-md-8">
                @Html.DisplayFor(q => item.Quantity)
            </div>
            <div class="col-md-8">
                @Html.DisplayFor(up => item.UnitPrice)
            </div>
        </div>
    }
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.OrderId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.OrderId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DeliveryName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DeliveryName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DeliveryAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DeliveryAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>

        </dl>
    </div>
    <form action="https://www.payfast.co.za/eng/process" name="form_df5cd28df1000f9ea1dfa24fbd0dae9b" onsubmit="return click_df5cd28df1000f9ea1dfa24fbd0dae9b( this );" method="post">
        <input type="hidden" name="cmd" value="_paynow">
        <input type="hidden" name="receiver" value="12900399">
        <input type="hidden" name="item_name" value="@Model.DeliveryName">
        <input type="hidden" name="amount" value="@Model.TotalPrice.ToString("0.##")">
        <input type="hidden" name="item_description" value="Product">
        <input type="hidden" name="return_url" value="https://petplatform.azurewebsites.net/PaymentSuccess">
        <input type="hidden" name="cancel_url" value="https://petplatform.azurewebsites.net/PaymentCancel">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirm Order" class="btn btn-default" />
            </div>
        </div>
    </form>

</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DoctorPatient/DoctorPatient/Views/Orders/Edit.cshtml
@model DoctorPatient.Models.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorPatient/DoctorPatient/Views/Orders/Index.cshtml
@model IEnumerable<DoctorPatient.Models.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Index", "Orders", FormMethod.Get))
{
    <div class="row form-group">
        <div class="col-md-2">
            <label>Search Orders by Id or Text:</label>
        </div>
        <div class="col-md-3">
            @Html.TextBox("OrderSearch", null, new { @class = "form-control", @placeholder = "Search Orders" })
        </div>
        <div class="col-md-2">
            <label>Search between dates:</label>
        </div>
        <div class="col-md-2">
            <input type="date" id="StartDate" name="StartDate" class="form-control" value="@Request.QueryString["StartDate"]"/>
        </div>
        <div class="col-md-2">
            <input type="date" id="EndDate" name="EndDate" class="form-control" value="@Request.QueryString["EndDate"]"/> 
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </div>
}

<p>
    @Html.ActionLink("Create New", "Review")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.ActionLink("User", "Index", new
            {
                orderSortOrder = ViewBag.UserSort,
                orderSearch = ViewBag.CurrentOrderSearch, 
                startdate = ViewBag.StartDate,
                endDate = ViewBag.EndDate
            })
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DeliveryAddress)
        </th>
        <th>
            @Html.ActionLink("Total Price", "Index", new
               {
                   orderSortOrder = ViewBag.PriceSort,
                   orderSearch = ViewBag.CurrentOrderSearch, 
                   startdate = ViewBag.StartDate,
                   endDate = ViewBag.EndDate
               })
        </th>
        <th>
            @Html.ActionLink("Time of Order", "Index", new
               {
                   orderSortOrder = ViewBag.DateSort, 
                   orderSearch = ViewBag.CurrentOrderSearch,
                   startdate = ViewBag.StartDate, 
                   endDate = ViewBag.EndDate
               })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeliveryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeliveryAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.OrderId }) 
        </td>
    </tr>
}

</table>

DoctorPatient/DoctorPatient/Views/Orders/PaymentCancel.cshtml
@{
    ViewBag.Title = "PaymentFailure";
}

<h2 style="color:crimson">Your order has failed to process</h2>
<br/>
<hr />
<h6 style="color:cadetblue">Click below to go back to your order.</h6>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DoctorPatient/DoctorPatient/Views/Orders/PaymentSuccess.cshtml
@{
    ViewBag.Title = "View";
}

<h4 style="color:darkcyan">Your order has been successfully processed</h4>
<hr/>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DoctorPatient/DoctorPatient/Views/Orders/Review.cshtml
@model DoctorPatient.Models.Order

@{
    ViewBag.Title = "Review Your Order";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Orders")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-2">
            <label>
                Item
            </label>
        </div>
        <div class="col-md-2">
            <label>
                Quantity
            </label>
        </div>
        <div class="col-md-2">
            <label>
                Unit Price
            </label>
        </div>
    </div>

    @foreach (var item in Model.OrderLines)
    {
        <div class="row">
            <div class="col-md-2">
                @Html.DisplayFor(modelItem => item.Product.Name)
            </div>
            <div class="col-md-2">
                @Html.DisplayFor(modelItem => item.Quantity)
            </div>
            <div class="col-md-2">
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </div>
        </div>
    }
    <br/><br/>
    <div class="form-group">
        @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.TotalPrice)
            @Html.HiddenFor(model => model.TotalPrice)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.UserId)
            @Html.HiddenFor(model => model.UserId)
        </div>
    </div>
  
    <div class="form-group">
        @Html.LabelFor(model => model.DeliveryName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeliveryName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeliveryName, "", new { @class = "text-danger" })
        </div>
    </div>
    <br/>
    <h4 style="color:#18bc9c">If you create this order it will be delivered to this address:</h4><br/>
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeliveryAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Order" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Edit Cart", "Index", "Cart")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorPatient/DoctorPatient/Views/Orders/_CheckoutDetails.cshtml
@model DoctorPatient.Models.Order

@{
    ViewBag.Title = "Order Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.OrderId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.OrderId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DeliveryName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DeliveryName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DeliveryAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DeliveryAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TotalPrice)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>

        </dl>
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>